### PR TITLE
Puppetize discordirc

### PR DESCRIPTION
**Pull request by MacFan4000**

### CODE REVIEW

**Review by RhinosF1 — APPROVED** [review]
Seems good but please take a backup of the old files first.

**Comment by Pix1234** [comment]
This shouldnt of been merged, you cant use channel ids, spacing...

**Comment by MacFan4000** [comment]
> This shouldnt of been merged, you cant use channel ids, spacing...

You can use channel ids. It says so in the docs and we’ve verified that it works.

**Comment by RhinosF1** [comment]
> This shouldnt of been merged, you cant use channel ids, spacing...

The channel IDs change was made prior to this change and tested as they are apparently a few channel renames going on and they thought it would be easier.

Otherwise, there should have been no change to what's on production prior to this PR as it was only supposed to allow making config public. In theory if it worked it would be no-op.

**Pull request merged**
