### PR TITLE
Add root for sario on bots1

### PR DESCRIPTION
**Pull request by RhinosF1**
Sario is a keen tester with us. I propose we give him push access to the sopel related repos, root on bots1, icinga access, acl*security and logs channel on irc. 

Checklist:

- [x] Approval from RhinosF1
- [x] Approval from Reception123 for Miraheze SRE
- [x] Approval from MacFan or Void
- [x] Miraheze NDA

### CODE REVIEW

**Comment by dmehus** [comment]
No objections here, but I don't see Sario listed at https://meta.miraheze.org/wiki/Board/NDAs/en, unless this was only recently submitted and approved and Owen's yet to update the list?

**Comment by RhinosF1** [comment]
> No objections here, but I don't see Sario listed at https://meta.miraheze.org/wiki/Board/NDAs/en, unless this was only recently submitted and approved and Owen's yet to update the list?

That's why the box saying Miraheze NDA isn't ticked.

**Comment by dmehus** [comment]
> > No objections here, but I don't see Sario listed at https://meta.miraheze.org/wiki/Board/NDAs/en, unless this was only recently submitted and approved and Owen's yet to update the list?
> 
> That's why the box saying Miraheze NDA isn't ticked.

Ah, okay. That makes sense. So these are just the preliminary commits until this is finalized, essentially?

**Comment by RhinosF1** [comment]
Yep

**Comment by dmehus** [comment]
> Yep

Great! :)

**Comment by Reception123** [comment]
Don't have any particular comments or objections.

**Comment by sario528** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCasBlmfMFw1DAH/t8KVJNKYwkmoxlpiwV75N7wpbk0jPcGtdDkk6z8DaQJSaQoNrqG03ge1eGHfYxDUF9zc1mxhOttLS39Dvp0dGYI/O+yLE2Iv+42mY9xvXQeITTrAQypTcLwCVYT9/9MyWoz2tztnhwl0SdH/NxJQWyS6Q1Q9VpIO/N76HgyavPP6V3+n7D3+ML0rvg0b1Ps4HOp+8X5ogeewo3I6+L0O319EPwHA+Oo1PlFAKZL7FXc2O/3dMqUaB2TdxuXTIwQpdLFs0Rq+1PeY3aPqp6+ro2I6OO/g5HGgXdU8B3YWdAyWm5120J0yzUI9NlrjetLZk3wx5QsPRwKkFxGhK8C8RnscqWE9o6UC1cBm522BJ+yAANs5gjLdWF1xslQo1Wq7+LQRymEnTQd0hhEryORDhakTaIFwM1gwoh8MW9kIx2SAX0VvejShXyPIBBZ2VX3eHD+UTS/Zp1tWeL68ubdIN9rvwiEnU0KGjYQO/3eXuwJHMGuUu/LVbFt+42j2HjmjoG42e0qJcQ03d4Apk31lKm8xZACUmjLDxgM2WPAVYh5tR8puOt8SzVoeEGW6nvL29/TW67+FH82/ZYWvBbEGUMV2SwWYWXoOMp4DUmQa89t1U02I17cJfvJobYGJjzYGA1RYFqYVBs7AMPi2gSDmeRnws9O/w==

**Review by MacFan4000 — APPROVED** [review]

**Comment by RhinosF1** [comment]
NDA got. I'll add acl*security.

We said Sario for shell username. I'll add acl*security on phab now and invite you to GitHub.

Myself or another member of SRE can do this PR as soon as they have access.

**Comment by MacFan4000** [comment]
icinga done

**Pull request merged**
