### PR TITLE
mhlibera: re-allow coco per discord mods

### PR DESCRIPTION
**Pull request by dmehus**
Implements step 2 of a three-step process that would see Cocopuff2018 eventually unbanned from Discord, subject, of course, to the same restrictions currently in place on IRC, which for ease of recall are published at https://www.irccloud.com/pastebin/poFUSG3P/.

@Reception123, can you merge the above, please, in your dual capacity as MirahezeBots operator and Discord/IRC platform moderator? Thank you. :)

### CODE REVIEW

**Comment by dmehus** [comment]
@RhinosF1 I mean, this PR already existed. You could've just merged this and added your comments with your close. :P

**Comment by RhinosF1** [comment]
Didn't see this PR. Will copy my comment over for the record. Please ping as discussed when Discord ban has actually been removed and 2 users are informed.

**Comment by dmehus** [comment]
> Didn't see this PR. Will copy my comment over for the record. Please ping as discussed when Discord ban has actually been removed and 2 users are informed.

No problem. Sounds good. I haven't implemented the Discord unban yet, as I'd like to have @Reception123 reach out to the two users and provide them with Cocopuff2018's current Discord account ID first.

**Comment by RhinosF1** [comment]
```
For when discord ban is lifted, 2 users with IBANs must be informed of this and we must be alerted as soon as they are any complaints regarding use of the relay.

Coco should be reminded that any misuse will be taken extremely seriously if it occurs and I will be banging on the doors of moderators if I have to deal with it.`
```

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Required steps to inform complainants still haven't been done.

**Review by RhinosF1 — APPROVED** [review]
Pre steps finally done

**Pull request merged**
