### PR TITLE
Add Ballmedia Discord and IRC channel IDs

### PR DESCRIPTION
**Pull request by dmehus**
As requested by @Agent-Isai

### CODE REVIEW

**Comment by MacFan4000** [comment]
We need to create a completely separate config file as well as add a service. Each instance can only communicate with one discord server.

**Comment by dmehus** [comment]
> We need to create a completely separate config file as well as add a service. Each instance can only communicate with one discord server.

Hrm, so what do you mean by this? We already have multiple Discord servers in this config, so I'm not sure what you mean?

**Comment by MacFan4000** [comment]
> > We need to create a completely separate config file as well as add a service. Each instance can only communicate with one discord server.
> 
> Hrm, so what do you mean by this? We already have multiple Discord servers in this config, so I'm not sure what you mean?

No we don’t this one only relays to the official miraheze discord.

**Comment by dmehus** [comment]
> > > We need to create a completely separate config file as well as add a service. Each instance can only communicate with one discord server.
> > 
> > 
> > Hrm, so what do you mean by this? We already have multiple Discord servers in this config, so I'm not sure what you mean?
> 
> No we don’t this one only relays to the official miraheze discord.

Ah, okay, thanks. So there's no public repo with a separate file? As in the case with the Buffalo NAS Discord relay, it's just a private config file stored on the server?

**Pull request closed without merging**
